[I 16:11:49.299 NotebookApp] [nb_conda_kernels] enabled, 13 kernels found
[I 16:11:49.413 NotebookApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 16:11:50.246 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[W 2023-04-14 16:11:51.133 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2023-04-14 16:11:51.138 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-14 16:11:51.138 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-14 16:11:51.138 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-14 16:11:51.138 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-14 16:11:51.138 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-14 16:11:51.138 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-04-14 16:11:51.139 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2023-04-14 16:11:51.147 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[I 2023-04-14 16:11:51.149 LabApp] JupyterLab extension loaded from /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/jupyterlab
[I 2023-04-14 16:11:51.149 LabApp] JupyterLab application directory is /om/weka/fiete/leokoz8/envs/rnns-of-rnns-env/share/jupyter/lab
[I 16:11:51.155 NotebookApp] Serving notebooks from local directory: /rdma/vast-rdma/vast/fiete/leokoz8/code/rnns-of-rnns
[I 16:11:51.155 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 16:11:51.155 NotebookApp] http://node072:9000/
[I 16:11:51.155 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 16:12:49.664 NotebookApp] 302 GET / (172.16.24.254) 0.840000ms
/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 16:13:09.933 NotebookApp] Notebook notebooks/Analyzing Trained GW.ipynb is not trusted
Exception in callback <TaskWakeupMethWrapper object at 0x2b5fb9a876d0>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x2b5fb9a876d0>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-6' coro=<HTTP1ServerConnection._server_request_loop() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/jupyter_client/manager.py:71>> is being executed.
Exception in callback <TaskWakeupMethWrapper object at 0x2b5fb95e86a0>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x2b5fb95e86a0>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-10' coro=<HTTP1ServerConnection._server_request_loop() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /kernel...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/site-packages/jupyter_client/manager.py:71>> is being executed.
[I 16:13:10.402 NotebookApp] Kernel started: eb41e7b9-5d3f-4403-aafd-71d1d1af96df, name: conda-env-leokoz8-rnns-of-rnns-env-py
/om/user/leokoz8/envs/rnns-of-rnns-env/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[I 16:15:10.462 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:17:10.397 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:19:10.380 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:21:10.376 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:23:10.385 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:27:10.878 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:31:10.396 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:33:10.381 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:35:10.425 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:37:10.860 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:39:10.395 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:41:10.407 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:43:10.450 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:45:10.846 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:49:10.364 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:51:10.860 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:53:10.417 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:55:10.495 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 16:57:10.401 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 17:01:10.461 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 17:03:10.437 NotebookApp] Saving file at /notebooks/Analyzing Trained GW.ipynb
[I 17:07:10.871 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:13:10.447 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[W 17:14:17.899 NotebookApp] Notebook notebooks/neurogym_testing.ipynb is not trusted
[I 17:14:18.620 NotebookApp] Kernel started: ceda7b32-8c7c-489a-bcb4-fd1121a1c4f3, name: conda-env-leokoz8-rnns-of-rnns-env-py
[I 17:15:10.852 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:17:10.904 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[W 17:18:28.967 NotebookApp] Notebook notebooks/Loading Pretrained RNNs.ipynb is not trusted
[I 17:18:29.566 NotebookApp] Kernel started: b860bc77-549b-4827-8d8e-29243e29fc33, name: conda-env-leokoz8-rnns-of-rnns-env-py
[I 17:21:10.408 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:22:29.918 NotebookApp] Saving file at /notebooks/Loading Pretrained RNNs.ipynb
[W 17:22:29.918 NotebookApp] Notebook notebooks/Loading Pretrained RNNs.ipynb is not trusted
[I 17:23:10.879 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:25:10.372 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:27:10.397 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:29:10.403 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:31:10.407 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:33:10.404 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:35:10.411 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:37:10.414 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:39:10.401 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:41:10.413 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:43:10.410 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:45:10.404 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:47:10.426 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:53:10.421 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 17:58:43.940 NotebookApp] Starting buffering for b860bc77-549b-4827-8d8e-29243e29fc33:df98500bb3b24889859388407c43be8b
[I 17:58:43.942 NotebookApp] Starting buffering for ceda7b32-8c7c-489a-bcb4-fd1121a1c4f3:2921a4196239482599cf550ddc9de228
[I 17:58:43.943 NotebookApp] Starting buffering for eb41e7b9-5d3f-4403-aafd-71d1d1af96df:391dd78e12f34884819860a7cd715499
[I 17:59:23.364 NotebookApp] Restoring connection for b860bc77-549b-4827-8d8e-29243e29fc33:df98500bb3b24889859388407c43be8b
[I 17:59:23.406 NotebookApp] Restoring connection for ceda7b32-8c7c-489a-bcb4-fd1121a1c4f3:2921a4196239482599cf550ddc9de228
[I 17:59:23.451 NotebookApp] Restoring connection for eb41e7b9-5d3f-4403-aafd-71d1d1af96df:391dd78e12f34884819860a7cd715499
[I 17:59:25.862 NotebookApp] Starting buffering for b860bc77-549b-4827-8d8e-29243e29fc33:df98500bb3b24889859388407c43be8b
[I 17:59:25.863 NotebookApp] Starting buffering for ceda7b32-8c7c-489a-bcb4-fd1121a1c4f3:2921a4196239482599cf550ddc9de228
[I 17:59:25.863 NotebookApp] Starting buffering for eb41e7b9-5d3f-4403-aafd-71d1d1af96df:391dd78e12f34884819860a7cd715499
[I 18:14:43.725 NotebookApp] Restoring connection for eb41e7b9-5d3f-4403-aafd-71d1d1af96df:391dd78e12f34884819860a7cd715499
[I 18:14:43.730 NotebookApp] Restoring connection for ceda7b32-8c7c-489a-bcb4-fd1121a1c4f3:2921a4196239482599cf550ddc9de228
[I 18:14:43.766 NotebookApp] Restoring connection for b860bc77-549b-4827-8d8e-29243e29fc33:df98500bb3b24889859388407c43be8b
[I 18:37:10.619 NotebookApp] Saving file at /notebooks/Analyzing Trained GW Performance.ipynb
[I 18:50:58.636 NotebookApp] Starting buffering for eb41e7b9-5d3f-4403-aafd-71d1d1af96df:391dd78e12f34884819860a7cd715499
[I 18:50:58.645 NotebookApp] Starting buffering for ceda7b32-8c7c-489a-bcb4-fd1121a1c4f3:2921a4196239482599cf550ddc9de228
[I 18:50:58.655 NotebookApp] Starting buffering for b860bc77-549b-4827-8d8e-29243e29fc33:df98500bb3b24889859388407c43be8b
slurmstepd: error: *** JOB 30214189 ON node072 CANCELLED AT 2023-04-15T04:11:42 DUE TO TIME LIMIT ***
